/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.4.
* Website: https://github.com/overturetool/vdm2c
*/

#include "Controller.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void Controller_free_fields(struct Controller *this)
{
			vdmFree(this->m_Controller_servoLeft);
			vdmFree(this->m_Controller_servoRight);
			vdmFree(this->m_Controller_sensorRightVal);
			vdmFree(this->m_Controller_sensorLeftVal);
	}

static void Controller_free(struct Controller *this)
{
	--this->_Controller_refs;
	if (this->_Controller_refs < 1)
	{
		Controller_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z17fieldInitializer7EV()	{

TVP ret_12 = newInt(4)
;

return ret_12;
}


/* Controller.vdmrt 20:12 */
 static  void _Z12control_loopEV(ControllerCLASS this)	{

TVP andResult_1 = newBoolGC(false, &andResult_1)
;

if ( toBool(vdmLessThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorRightVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	if ( toBool(vdmLessThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorLeftVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	andResult_1 = newBoolGC(true, NULL);;;
/* Controller.vdmrt 23:9 */
if ( toBool(andResult_1) )
	/* Controller.vdmrt 24:14 */
	{
/* Controller.vdmrt 25:33 */
TVP embeding_1 = vdmMinusGC(CALL_FUNC(RealPort, RealPort, g_HardwareInterface_forwardSpeed, CLASS_RealPort__Z8getValueEV), &embeding_1)
;
/* Controller.vdmrt 25:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoRight), CLASS_RobotServo__Z8setServoER, embeding_1);
/* Controller.vdmrt 26:32 */
TVP embeding_2 = CALL_FUNC(RealPort, RealPort, g_HardwareInterface_forwardSpeed, CLASS_RealPort__Z8getValueEV)
;
/* Controller.vdmrt 26:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoLeft), CLASS_RobotServo__Z8setServoER, embeding_2);
}
;

TVP andResult_2 = newBoolGC(false, &andResult_2)
;

if ( toBool(vdmLessThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorRightVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	if ( toBool(vdmGreaterThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorLeftVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	andResult_2 = newBoolGC(true, NULL);;;
/* Controller.vdmrt 29:9 */
if ( toBool(andResult_2) )
	/* Controller.vdmrt 30:14 */
	{
/* Controller.vdmrt 31:33 */
TVP embeding_3 = vdmMinusGC(CALL_FUNC(RealPort, RealPort, g_HardwareInterface_forwardRotate, CLASS_RealPort__Z8getValueEV), &embeding_3)
;
/* Controller.vdmrt 31:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoRight), CLASS_RobotServo__Z8setServoER, embeding_3);
/* Controller.vdmrt 32:32 */
TVP embeding_4 = CALL_FUNC(RealPort, RealPort, g_HardwareInterface_backwardRotate, CLASS_RealPort__Z8getValueEV)
;
/* Controller.vdmrt 32:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoLeft), CLASS_RobotServo__Z8setServoER, embeding_4);
}
;

TVP andResult_3 = newBoolGC(false, &andResult_3)
;

if ( toBool(vdmGreaterThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorRightVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	if ( toBool(vdmLessThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorLeftVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	andResult_3 = newBoolGC(true, NULL);;;
/* Controller.vdmrt 35:9 */
if ( toBool(andResult_3) )
	/* Controller.vdmrt 36:14 */
	{
/* Controller.vdmrt 37:33 */
TVP embeding_5 = vdmMinusGC(CALL_FUNC(RealPort, RealPort, g_HardwareInterface_backwardRotate, CLASS_RealPort__Z8getValueEV), &embeding_5)
;
/* Controller.vdmrt 37:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoRight), CLASS_RobotServo__Z8setServoER, embeding_5);
/* Controller.vdmrt 38:32 */
TVP embeding_6 = CALL_FUNC(RealPort, RealPort, g_HardwareInterface_forwardRotate, CLASS_RealPort__Z8getValueEV)
;
/* Controller.vdmrt 38:13 */
CALL_FUNC(RobotServo, RobotServo, GET_FIELD_PTR_GC(Controller, Controller, this, servoLeft), CLASS_RobotServo__Z8setServoER, embeding_6);
}
;

TVP andResult_4 = newBoolGC(false, &andResult_4)
;

if ( toBool(vdmGreaterThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorRightVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	if ( toBool(vdmGreaterThanGC(CALL_FUNC(RobotSensor, RobotSensor, GET_FIELD_PTR_GC(Controller, Controller, this, sensorLeftVal), CLASS_RobotSensor__Z10getReadingEV), newIntGC(150, NULL), NULL)) )
	
	andResult_4 = newBoolGC(true, NULL);;;
/* Controller.vdmrt 41:9 */
if ( toBool(andResult_4) )
	/* Controller.vdmrt 42:14 */
	{
//Skip
};;
}



 void Controller_const_init()	{

numFields_3 = _Z17fieldInitializer7EV();

return ;
}



 void Controller_const_shutdown()	{

vdmFree(numFields_3);

return ;
}



 void Controller_static_init()	{

return ;
}



 void Controller_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForController  [] ={

{0,0,((VirtualFunctionPointer) _Z10ControllerE10CRobotServo10CRobotServo11CRobotSensor11CRobotSensor),},
{0,0,((VirtualFunctionPointer) _Z12control_loopEV),},
{0,0,((VirtualFunctionPointer) _Z10ControllerEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
ControllerCLASS Controller_Constructor(ControllerCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (ControllerCLASS) malloc(sizeof(struct Controller));
	}

	if(this_ptr!=NULL)
	{
	
			
		// Controller init
		this_ptr->_Controller_id = CLASS_ID_Controller_ID;
		this_ptr->_Controller_refs = 0;
		this_ptr->_Controller_pVTable=VTableArrayForController;

							this_ptr->m_Controller_servoLeft= NULL ;
						this_ptr->m_Controller_servoRight= NULL ;
						this_ptr->m_Controller_sensorRightVal= NULL ;
						this_ptr->m_Controller_sensorLeftVal= NULL ;
			}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	ControllerCLASS ptr=Controller_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_Controller_id, &ptr->_Controller_refs, (freeVdmClassFunction)&Controller_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* Controller.vdmrt 11:12 */
 TVP _Z10ControllerE10CRobotServo10CRobotServo11CRobotSensor11CRobotSensor(ControllerCLASS this, TVP servL, TVP servR, TVP sensRightVal, TVP sensLeftVal)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, Controller);
}
;
/* Controller.vdmrt 14:19 */
TVP field_tmp_6 = vdmCloneGC(servL, &field_tmp_6)
;

SET_FIELD_PTR_GC(Controller, Controller, this, servoLeft, field_tmp_6);

vdmFree(field_tmp_6);
/* Controller.vdmrt 15:18 */
TVP field_tmp_7 = vdmCloneGC(servR, &field_tmp_7)
;

SET_FIELD_PTR_GC(Controller, Controller, this, servoRight, field_tmp_7);

vdmFree(field_tmp_7);
/* Controller.vdmrt 16:24 */
TVP field_tmp_8 = vdmCloneGC(sensRightVal, &field_tmp_8)
;

SET_FIELD_PTR_GC(Controller, Controller, this, sensorRightVal, field_tmp_8);

vdmFree(field_tmp_8);
/* Controller.vdmrt 17:21 */
TVP field_tmp_9 = vdmCloneGC(sensLeftVal, &field_tmp_9)
;

SET_FIELD_PTR_GC(Controller, Controller, this, sensorLeftVal, field_tmp_9);

vdmFree(field_tmp_9);

return __buf;
}


/* Controller.vdmrt 1:7 */
 TVP _Z10ControllerEV(ControllerCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, Controller);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order
	TVP numFields_3 =  NULL ;
					
