/**
* This file is generated by Overture's VDM-to-C code generator version 0.1.4.
* Website: https://github.com/overturetool/vdm2c
*/

#include "HardwareInterface.h"
#include <stdio.h>
#include <string.h>


/* -------------------------------
 *
 * Memory management methods
 *
 --------------------------------- */

void HardwareInterface_free_fields(struct HardwareInterface *this)
{
						vdmFree(this->m_HardwareInterface_leftVal);
			vdmFree(this->m_HardwareInterface_rightVal);
			vdmFree(this->m_HardwareInterface_total_energy_used);
			vdmFree(this->m_HardwareInterface_servo_right_out);
			vdmFree(this->m_HardwareInterface_servo_left_out);
	}

static void HardwareInterface_free(struct HardwareInterface *this)
{
	--this->_HardwareInterface_refs;
	if (this->_HardwareInterface_refs < 1)
	{
		HardwareInterface_free_fields(this);
		free(this);
	}
}


/* -------------------------------
 *
 * Member methods 
 *
 --------------------------------- */
 

 static  TVP _Z18fieldInitializer20EV()	{
/* HardwareInterface.vdmrt 28:39 */
TVP ret_17 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_17;
}



 static  TVP _Z18fieldInitializer19EV()	{
/* HardwareInterface.vdmrt 26:40 */
TVP ret_18 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_18;
}



 static  TVP _Z18fieldInitializer18EV()	{
/* HardwareInterface.vdmrt 21:42 */
TVP ret_19 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_19;
}



 static  TVP _Z18fieldInitializer17EV()	{
/* HardwareInterface.vdmrt 19:33 */
TVP ret_20 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_20;
}



 static  TVP _Z18fieldInitializer16EV()	{
/* HardwareInterface.vdmrt 17:32 */
TVP ret_21 = _Z8RealPortER(NULL, newReal(0.0))
;

return ret_21;
}



 static  TVP _Z18fieldInitializer15EV()	{
/* HardwareInterface.vdmrt 11:40 */
TVP ret_22 = _Z8RealPortER(NULL, newReal(1.0))
;

return ret_22;
}



 static  TVP _Z18fieldInitializer14EV()	{
/* HardwareInterface.vdmrt 9:39 */
TVP ret_23 = _Z8RealPortER(NULL, newReal(5.0))
;

return ret_23;
}



 static  TVP _Z18fieldInitializer13EV()	{
/* HardwareInterface.vdmrt 7:38 */
TVP ret_24 = _Z8RealPortER(NULL, newReal(4.0))
;

return ret_24;
}



 static  TVP _Z18fieldInitializer12EV()	{

TVP ret_25 = newInt(8)
;

return ret_25;
}



 void HardwareInterface_const_init()	{

numFields_6 = _Z18fieldInitializer12EV();

g_HardwareInterface_forwardSpeed = _Z18fieldInitializer13EV();

g_HardwareInterface_forwardRotate = _Z18fieldInitializer14EV();

g_HardwareInterface_backwardRotate = _Z18fieldInitializer15EV();

return ;
}



 void HardwareInterface_const_shutdown()	{

vdmFree(numFields_6);

vdmFree(g_HardwareInterface_forwardSpeed);

vdmFree(g_HardwareInterface_forwardRotate);

vdmFree(g_HardwareInterface_backwardRotate);

return ;
}



 void HardwareInterface_static_init()	{

return ;
}



 void HardwareInterface_static_shutdown()	{

return ;
}




/* -------------------------------
 *
 * VTable
 *
 --------------------------------- */
 
// VTable for this class
 static  struct VTable VTableArrayForHardwareInterface  [] ={

{0,0,((VirtualFunctionPointer) _Z17HardwareInterfaceEV),},
				
}  ;

// Overload VTables


/* -------------------------------
 *
 * Internal memory constructor
 *
 --------------------------------- */
 
 
HardwareInterfaceCLASS HardwareInterface_Constructor(HardwareInterfaceCLASS this_ptr)
{

	if(this_ptr==NULL)
	{
		this_ptr = (HardwareInterfaceCLASS) malloc(sizeof(struct HardwareInterface));
	}

	if(this_ptr!=NULL)
	{
	
			
		// HardwareInterface init
		this_ptr->_HardwareInterface_id = CLASS_ID_HardwareInterface_ID;
		this_ptr->_HardwareInterface_refs = 0;
		this_ptr->_HardwareInterface_pVTable=VTableArrayForHardwareInterface;

																this_ptr->m_HardwareInterface_leftVal= _Z18fieldInitializer16EV();
						this_ptr->m_HardwareInterface_rightVal= _Z18fieldInitializer17EV();
						this_ptr->m_HardwareInterface_total_energy_used= _Z18fieldInitializer18EV();
						this_ptr->m_HardwareInterface_servo_right_out= _Z18fieldInitializer19EV();
						this_ptr->m_HardwareInterface_servo_left_out= _Z18fieldInitializer20EV();
			}

	return this_ptr;
}

// Method for creating new "class"
static TVP new()
{
	HardwareInterfaceCLASS ptr=HardwareInterface_Constructor(NULL);

	return newTypeValue(VDM_CLASS, (TypedValueType)
			{	.ptr=newClassValue(ptr->_HardwareInterface_id, &ptr->_HardwareInterface_refs, (freeVdmClassFunction)&HardwareInterface_free, ptr)});
}



/* -------------------------------
 *
 * Public class constructors
 *
 --------------------------------- */ 
 

/* HardwareInterface.vdmrt 3:7 */
 TVP _Z17HardwareInterfaceEV(HardwareInterfaceCLASS this)	{

TVP __buf = NULL
;

if ( this == NULL )
	
	{

__buf = new();

this = TO_CLASS_PTR(__buf, HardwareInterface);
}
;

return __buf;
}




/* -------------------------------
 *
 * Global class fields
 *
 --------------------------------- */
 
// initialize globals - this is done last since they are declared in the header but uses init functions which are printet in any order
	TVP numFields_6 =  NULL ;
		TVP g_HardwareInterface_forwardSpeed =  NULL ;
		TVP g_HardwareInterface_forwardRotate =  NULL ;
		TVP g_HardwareInterface_backwardRotate =  NULL ;
						
